2023-04-26 18:14:30.124301 2023-04-26 18:14:30.122 39 WARNING keystone.common.rbac_enforcer.enforcer [None req-cf38839f-ae70-45b8-9241-d2b257e8e029 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-26 18:14:31.096569 2023-04-26 18:14:31.095 38 WARNING keystone.common.rbac_enforcer.enforcer [None req-0d9ed63a-ac11-4a42-a41a-24ab3db0d80e 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-26 18:14:38.132943 2023-04-26 18:14:38.131 37 WARNING keystone.common.rbac_enforcer.enforcer [None req-7382d4d7-3b2d-4cf7-936b-c52b597abd6e 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-26 18:15:58.597036 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application [None req-fb67936e-4281-4762-b493-607fbfe712da 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:15:58.597108 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:15:58.597161 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:15:58.597174 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:15:58.597184 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:15:58.597196 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:15:58.597207 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:15:58.597218 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:15:58.597229 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:15:58.597270 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:15:58.597280 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:15:58.597291 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:15:58.597301 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:15:58.597313 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:15:58.597335 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:15:58.597347 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:15:58.597358 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:15:58.597435 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:15:58.597450 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:15:58.597461 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:15:58.597479 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:15:58.597492 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:15:58.597503 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:15:58.597514 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:15:58.597525 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:15:58.597551 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:15:58.597562 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:15:58.597572 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:15:58.597583 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:15:58.597593 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:15:58.597609 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:15:58.597620 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:15:58.597630 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:15:58.597640 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:15:58.597651 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:15:58.597673 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:15:58.597684 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:15:58.597695 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:15:58.597705 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:15:58.597715 2023-04-26 18:15:58.579 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:08.571727 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application [None req-93059a10-3bc4-4917-80a5-363240ab0020 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:08.571804 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:08.571847 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:08.571870 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:08.571886 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:08.571905 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:08.571922 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:08.571938 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:08.571954 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:08.572011 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:08.572032 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:08.572048 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:08.572063 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:16:08.572079 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:16:08.572095 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:16:08.572110 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:16:08.572163 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:08.572185 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:08.572201 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:08.572218 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:08.572242 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:08.572259 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:08.572276 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:08.572306 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:08.572322 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:08.572339 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:08.572374 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:08.572391 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:08.572407 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:08.572424 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:08.572440 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:08.572456 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:08.572471 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:16:08.572488 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:16:08.572504 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:16:08.572520 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:16:08.572536 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:16:08.572552 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:16:08.572568 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:08.572584 2023-04-26 18:16:08.555 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:24.551928 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application [None req-6cac3699-9f71-4700-a2ad-63ba689a08d9 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:16:24.552021 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:24.552036 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:24.552049 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:24.552060 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:24.552072 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:24.552084 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:24.552095 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:24.552139 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:24.552159 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:24.552171 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:24.552198 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:24.552210 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-26 18:16:24.552222 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-26 18:16:24.552233 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-26 18:16:24.552244 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-26 18:16:24.552256 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-26 18:16:24.552268 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-26 18:16:24.552279 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-26 18:16:24.552291 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-26 18:16:24.552303 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:24.552314 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:24.552326 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:24.552337 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:24.552349 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:24.552360 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:24.552371 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:24.552383 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:24.552394 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:24.552406 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:24.552417 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:24.552428 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:24.552440 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:24.552451 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:24.552462 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:24.552485 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:24.552497 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-26 18:16:24.552509 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-26 18:16:24.552520 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-26 18:16:24.552531 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-26 18:16:24.552543 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-26 18:16:24.552554 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-26 18:16:24.552565 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:16:24.552577 2023-04-26 18:16:24.544 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:26.271790 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application [None req-34b07438-249a-4020-9791-90f280c624c4 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-26 18:16:26.271843 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:26.271856 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:26.271867 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:26.271877 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:26.271889 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:26.271900 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:26.271910 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:26.271921 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:26.271932 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:26.271943 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:26.271954 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:26.271964 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-26 18:16:26.271975 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-26 18:16:26.272023 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-26 18:16:26.272051 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-26 18:16:26.272063 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:26.272074 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:26.272085 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-26 18:16:26.272096 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:16:26.272106 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-26 18:16:26.272146 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:16:26.272164 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:26.272175 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:26.272186 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:26.272197 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:26.272207 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:26.272227 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:26.272237 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:26.272248 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:26.272259 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:26.272269 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:26.272280 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:26.272291 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:26.272301 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:26.272312 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:26.272330 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-26 18:16:26.272341 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-26 18:16:26.272352 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-26 18:16:26.272363 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-26 18:16:26.272386 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-26 18:16:26.272398 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-26 18:16:26.272408 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-26 18:16:26.272419 2023-04-26 18:16:26.264 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:27.352459 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application [None req-579bad37-e3f7-428f-a7ec-28b4df071cda 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:27.352501 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:27.352512 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:27.352523 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:27.352533 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:27.352543 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:27.352558 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:27.352568 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:27.352585 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:27.352609 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:27.352624 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:27.352634 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:27.352643 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:16:27.352654 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:16:27.352663 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:16:27.352673 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:16:27.352686 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:27.352696 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:27.352706 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:27.352715 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:27.352755 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:27.352768 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:27.352778 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:27.352788 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:27.352797 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:27.352807 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:27.352816 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:27.352826 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:27.352836 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:27.352845 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:27.352855 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:27.352865 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:27.352874 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:16:27.352884 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:16:27.352894 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:16:27.352904 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:16:27.352913 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:16:27.352923 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:16:27.352933 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:27.352942 2023-04-26 18:16:27.342 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:37.729336 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application [None req-b07fb0d6-3824-453a-a830-196a312a441f 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:16:37.729381 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:37.729393 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:37.729404 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:37.729414 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:37.729440 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:37.729451 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:37.729461 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:37.729471 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:37.729481 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:37.729491 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:37.729501 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:37.729510 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-26 18:16:37.729520 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-26 18:16:37.729530 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-26 18:16:37.729540 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-26 18:16:37.729558 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-26 18:16:37.729570 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-26 18:16:37.729586 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-26 18:16:37.729598 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-26 18:16:37.729607 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:37.729617 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:37.729627 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:37.729636 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:37.729645 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:37.729655 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:37.729665 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:37.729675 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:37.729695 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:37.729706 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:37.729716 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:37.729726 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:37.729735 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:37.729745 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:37.729755 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:37.729764 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:37.729774 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-26 18:16:37.729784 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-26 18:16:37.729793 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-26 18:16:37.729803 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-26 18:16:37.729813 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-26 18:16:37.729822 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-26 18:16:37.729832 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:16:37.729841 2023-04-26 18:16:37.723 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:39.046438 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application [None req-ca9ec723-8f2b-407e-9453-02a38a6b3fd1 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-26 18:16:39.046657 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:39.046669 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:39.046680 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:39.046690 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:39.046700 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:39.046710 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:39.046720 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:39.046730 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:39.046759 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:39.046770 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:39.046780 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:39.046790 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-26 18:16:39.046800 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-26 18:16:39.046810 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-26 18:16:39.046837 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-26 18:16:39.046847 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:39.046857 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:39.046866 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-26 18:16:39.046876 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:16:39.046886 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-26 18:16:39.046896 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:16:39.046905 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:39.046915 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:39.046926 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:39.046936 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:39.046945 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:39.046956 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:39.046965 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:39.046975 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:39.047006 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:39.047017 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:39.047027 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:39.047047 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:39.047058 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:39.047068 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:39.047078 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-26 18:16:39.047087 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-26 18:16:39.047097 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-26 18:16:39.047107 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-26 18:16:39.047138 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-26 18:16:39.047152 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-26 18:16:39.047162 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-26 18:16:39.047172 2023-04-26 18:16:39.040 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:16:39.871319 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application [None req-b8f5e428-a70f-4387-9174-f2f1ad238b18 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:39.871406 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:16:39.871424 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:16:39.871435 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:16:39.871446 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:16:39.871458 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:16:39.871469 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:16:39.871479 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:16:39.871513 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:16:39.871528 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:16:39.871539 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:16:39.871550 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:16:39.871561 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:16:39.871600 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:16:39.871613 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:16:39.871624 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:16:39.871635 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:16:39.871646 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:16:39.871656 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:16:39.871667 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:16:39.871678 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:16:39.871689 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:16:39.871700 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:16:39.871711 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:16:39.871722 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:16:39.871733 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:16:39.871743 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:16:39.871754 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:16:39.871765 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:16:39.871776 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:16:39.871786 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:16:39.871797 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:16:39.871808 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:16:39.871819 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:16:39.871830 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:16:39.871841 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:16:39.871854 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:16:39.871865 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:16:39.871889 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:16:39.871901 2023-04-26 18:16:39.865 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:19:35.427358 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application [None req-3cfa17a2-40f5-401e-bf17-685dba855d4e 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:19:35.429002 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:19:35.429036 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:19:35.429050 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:19:35.429059 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:19:35.429070 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:19:35.429079 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:19:35.429089 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:19:35.429099 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:19:35.429110 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:19:35.429142 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:19:35.429154 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:19:35.429164 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:19:35.429174 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:19:35.429184 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:19:35.429194 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:19:35.429206 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:19:35.429216 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:19:35.429227 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:19:35.429237 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:19:35.429247 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:19:35.429257 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:19:35.430674 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:19:35.430703 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:19:35.430721 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:19:35.430738 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:19:35.430756 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:19:35.430775 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:19:35.430793 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:19:35.430810 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:19:35.430825 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:19:35.430845 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:19:35.430861 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:19:35.430879 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:19:35.430897 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:19:35.430914 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:19:35.430931 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:19:35.430953 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:19:35.431003 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:19:35.431021 2023-04-26 18:19:35.421 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:19:50.807053 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application [None req-6e7b6338-7112-4acc-bc67-08f9d7e818ce 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:19:50.807177 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:19:50.807201 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:19:50.807230 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:19:50.807261 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:19:50.807275 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:19:50.807707 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:19:50.807749 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:19:50.807765 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:19:50.807780 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:19:50.807793 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:19:50.807807 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:19:50.807821 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-26 18:19:50.807835 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-26 18:19:50.807848 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-26 18:19:50.807862 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-26 18:19:50.807876 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-26 18:19:50.807890 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-26 18:19:50.807904 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-26 18:19:50.807919 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-26 18:19:50.807932 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:19:50.807946 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:19:50.807994 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:19:50.808013 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:19:50.808027 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:19:50.808041 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:19:50.808054 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:19:50.808068 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:19:50.808081 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:19:50.808095 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:19:50.808108 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:19:50.808175 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:19:50.808193 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:19:50.808207 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:19:50.808220 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:19:50.808234 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:19:50.808248 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-26 18:19:50.808265 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-26 18:19:50.808282 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-26 18:19:50.808296 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-26 18:19:50.808310 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-26 18:19:50.808324 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-26 18:19:50.808337 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-26 18:19:50.808351 2023-04-26 18:19:50.802 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:19:52.206850 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application [None req-91741d5f-5e13-44dd-a767-7e78a37333f9 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-26 18:19:52.206902 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:19:52.206913 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:19:52.206923 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:19:52.206937 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:19:52.206983 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:19:52.207054 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:19:52.207071 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:19:52.207087 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:19:52.207103 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:19:52.207119 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:19:52.207259 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:19:52.207274 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-26 18:19:52.207284 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-26 18:19:52.207293 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-26 18:19:52.207303 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-26 18:19:52.207313 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:19:52.207322 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:19:52.207332 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-26 18:19:52.207341 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:19:52.207351 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-26 18:19:52.207360 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-26 18:19:52.207370 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:19:52.207379 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:19:52.207413 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:19:52.207423 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:19:52.207432 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:19:52.207442 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:19:52.207451 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:19:52.207461 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:19:52.207470 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:19:52.207480 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:19:52.207489 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:19:52.207499 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:19:52.207508 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:19:52.207518 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:19:52.207538 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-26 18:19:52.207549 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-26 18:19:52.207558 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-26 18:19:52.207568 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-26 18:19:52.207578 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-26 18:19:52.207588 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-26 18:19:52.207597 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-26 18:19:52.207606 2023-04-26 18:19:52.202 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-26 18:19:53.079898 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application [None req-04f7283d-ac97-491d-a715-1cda157a3991 688fa3136a9c4096b7fe0e6cfb8fc873 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:19:53.079997 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-26 18:19:53.080014 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-26 18:19:53.080027 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-26 18:19:53.080039 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-26 18:19:53.080052 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-26 18:19:53.080065 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-26 18:19:53.080077 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-26 18:19:53.080090 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-26 18:19:53.080102 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-26 18:19:53.080146 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-26 18:19:53.080166 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-26 18:19:53.080179 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-26 18:19:53.080199 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-26 18:19:53.080213 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-26 18:19:53.080226 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-26 18:19:53.080260 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-26 18:19:53.080275 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-26 18:19:53.080287 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-26 18:19:53.080300 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-26 18:19:53.080313 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-26 18:19:53.080326 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-26 18:19:53.080339 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-26 18:19:53.080352 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     with Lock(
2023-04-26 18:19:53.080365 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-26 18:19:53.080377 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-26 18:19:53.080390 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-26 18:19:53.080403 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-26 18:19:53.080416 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-26 18:19:53.080428 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-26 18:19:53.080441 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-26 18:19:53.080454 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-26 18:19:53.080466 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-26 18:19:53.080480 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-26 18:19:53.080492 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-26 18:19:53.080505 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-26 18:19:53.080518 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-26 18:19:53.080531 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-26 18:19:53.080544 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-26 18:19:53.080556 2023-04-26 18:19:53.073 39 ERROR keystone.server.flask.application \x1b[00m
