2023-03-07 21:49:30.259 24 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-03-07 21:49:30.263 24 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-03-07 21:49:30.309 24 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-03-07 21:49:30.310 24 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-03-07 21:49:30.349 24 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-03-07 21:49:31.758 24 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-03-07 21:49:31.764 24 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-03-07 21:49:41.265 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-03-07 21:49:41.270 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-03-07 21:49:41.271 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-03-07 21:49:41.273 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-03-07 21:49:41.273 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-03-07 21:49:41.274 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-03-07 21:49:41.275 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-03-07 21:49:41.276 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-03-07 21:50:00.493 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created domain default
2023-03-07 21:50:00.575 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created project admin
2023-03-07 21:50:01.194 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created user admin
2023-03-07 21:50:01.220 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created role reader
2023-03-07 21:50:01.242 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created role member
2023-03-07 21:50:01.291 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created implied role where 225bd46afba74941ae3bc5ce2440f81f implies 42ed260db1e44055a228b039fe3a95d3
2023-03-07 21:50:01.319 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created role admin
2023-03-07 21:50:01.346 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created implied role where 566d95f1d5f646618e7a8e4cb2e11827 implies 225bd46afba74941ae3bc5ce2440f81f
2023-03-07 21:50:01.367 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Granted role admin on project admin to user admin.
2023-03-07 21:50:01.381 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Granted role admin on the system to user admin.
2023-03-07 21:50:01.402 33 WARNING py.warnings [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-03-07 21:50:01.409 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created region RegionOne
2023-03-07 21:50:01.459 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created public endpoint http://169.16.1.169:5000
2023-03-07 21:50:01.474 33 INFO keystone.cmd.bootstrap [None req-e9c70dd6-27d6-4aa7-940a-72c1a127600a - - - - - -] Created internal endpoint http://169.16.1.169:5000
2023-03-07 21:50:28.385 40 WARNING keystone.common.rbac_enforcer.enforcer [None req-c1ea16db-9e48-4891-89aa-c2bd7023207c 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-07 21:50:29.232 38 WARNING keystone.common.rbac_enforcer.enforcer [None req-666e9356-36eb-4cfa-918d-b5176e7de4e5 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-07 21:50:36.744 39 WARNING keystone.common.rbac_enforcer.enforcer [None req-3f252602-1bc1-4cc7-84d5-f0c98c775077 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application [None req-81914d7b-4556-419f-920f-f9c5dc278402 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:51:57.215 40 ERROR keystone.server.flask.application 
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application [None req-adb9a248-83e4-4433-a282-2543c57f5bdf 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:06.447 39 ERROR keystone.server.flask.application 
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application [None req-1be723cb-a278-4009-a085-4a2d370848c4 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:52:21.863 39 ERROR keystone.server.flask.application 
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application [None req-4cf7039c-f602-4b4f-bcc1-b1d3f53ad822 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-07 21:52:23.222 39 ERROR keystone.server.flask.application 
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application [None req-e3e63ca3-a5ac-4ae9-9e10-06a805d69d34 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:24.332 38 ERROR keystone.server.flask.application 
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application [None req-7d74b666-5f57-4b07-a697-9044393b3fd5 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:52:34.964 40 ERROR keystone.server.flask.application 
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application [None req-4ce8c40a-9b2c-44ea-87e3-da1c9ff7947f 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-07 21:52:36.143 40 ERROR keystone.server.flask.application 
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application [None req-80d723d6-4bc5-45fe-a62e-1c4e844f5b1c 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:52:36.918 39 ERROR keystone.server.flask.application 
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application [None req-ce11467a-6e20-4827-b716-3205ce2e7ad2 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:55:27.451 40 ERROR keystone.server.flask.application 
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application [None req-d25eadb3-1aa3-4448-a26e-470634f99e87 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:55:42.758 40 ERROR keystone.server.flask.application 
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application [None req-a2bacb1e-19c1-4280-883d-3ab2de745fee 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-07 21:55:43.872 40 ERROR keystone.server.flask.application 
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application [None req-697da2ca-f2fd-4761-918d-1b7168ff52a1 5fee93bc3ced4598b7496f2a0f56d5ec - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:55:44.592 39 ERROR keystone.server.flask.application 
2023-03-08 00:00:07.429 56 INFO keystone.common.fernet_utils [-] Starting key rotation with 2 key files: ['/etc/keystone/fernet-keys/0', '/etc/keystone/fernet-keys/1']
2023-03-08 00:00:07.431 56 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-03-08 00:00:07.434 56 INFO keystone.common.fernet_utils [-] Current primary key is: 1
2023-03-08 00:00:07.435 56 INFO keystone.common.fernet_utils [-] Next primary key will be: 2
2023-03-08 00:00:07.436 56 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 2
2023-03-08 00:00:07.436 56 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-03-08 02:19:14.745 39 WARNING py.warnings [None req-856f2f39-425e-4039-adcd-82f5be59d710 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_domains": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:14.962 38 WARNING py.warnings [None req-ee8c9ca9-8b23-4277-83ee-a734ed4a4fa6 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_project": "(role:admin and system_scope:all) or (role:admin and domain_id:%(target.project.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:15.269 40 WARNING py.warnings [None req-32aea978-524c-408e-9b0c-2df84c57a312 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_user": "(role:admin and system_scope:all) or (role:admin and token.domain.id:%(target.user.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:16.194 39 WARNING py.warnings [None req-293f034f-29f0-4846-baa2-8f8a98b889c2 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:16.586 38 WARNING py.warnings [None req-06731cdf-742a-499e-b186-e2f4ab86c7d9 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:18.367 39 WARNING py.warnings [None req-9c7950ba-1ee3-4ee7-b984-8ef44e9952ac 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_user": "(role:admin and system_scope:all) or (role:admin and token.domain.id:%(target.user.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:19.284 38 WARNING py.warnings [None req-1f9079b1-3671-4882-86f9-d10e386e0af2 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:19.673 40 WARNING py.warnings [None req-c61f8e98-08be-4b4b-a944-232722d993ed 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-03-08 02:19:22.905 40 WARNING py.warnings [None req-00486d0f-3209-4e28-8a82-2ceb483b50e0 5fee93bc3ced4598b7496f2a0f56d5ec 4642679439a9466a87cd8bbbbfc74fb7 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_system_grant_for_user": "role:admin and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

