2023-02-15 21:08:15.373 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-02-15 21:08:15.378 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-02-15 21:08:15.430 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-02-15 21:08:15.432 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-02-15 21:08:15.481 23 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-02-15 21:08:16.564 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-02-15 21:08:16.570 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-02-15 21:08:25.024 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-02-15 21:08:25.029 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-02-15 21:08:25.030 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-02-15 21:08:25.031 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-02-15 21:08:25.031 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-02-15 21:08:25.032 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-02-15 21:08:25.033 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-02-15 21:08:25.033 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-02-15 21:08:43.661 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created domain default
2023-02-15 21:08:43.753 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created project admin
2023-02-15 21:08:44.402 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created user admin
2023-02-15 21:08:44.428 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created role reader
2023-02-15 21:08:44.449 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created role member
2023-02-15 21:08:44.492 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created implied role where 99542eac939643a191464289043f8b74 implies 5a8e0ba4193b4358869139124fd5e5cf
2023-02-15 21:08:44.513 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created role admin
2023-02-15 21:08:44.546 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created implied role where a14fdf15264f49bd9606d102326fc4e6 implies 99542eac939643a191464289043f8b74
2023-02-15 21:08:44.566 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Granted role admin on project admin to user admin.
2023-02-15 21:08:44.578 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Granted role admin on the system to user admin.
2023-02-15 21:08:44.607 33 WARNING py.warnings [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-02-15 21:08:44.616 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created region RegionOne
2023-02-15 21:08:44.670 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created public endpoint http://169.16.1.142:5000
2023-02-15 21:08:44.688 33 INFO keystone.cmd.bootstrap [None req-b0cf8b6c-9de2-4545-a607-75e3e157a9b9 - - - - - -] Created internal endpoint http://169.16.1.142:5000
2023-02-15 21:09:12.871 39 WARNING keystone.common.rbac_enforcer.enforcer [None req-5949d307-7acf-44b9-bd61-169bb5bebbcd e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-15 21:09:13.720 40 WARNING keystone.common.rbac_enforcer.enforcer [None req-1ac3e679-5db9-4437-b853-9741faa1d65d e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-15 21:09:21.346 38 WARNING keystone.common.rbac_enforcer.enforcer [None req-95eb66b1-4cc2-4554-9030-eff7d336171b e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application [None req-80ca49ee-b080-4010-803c-74b6d795b207 e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:10:37.757 39 ERROR keystone.server.flask.application 
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application [None req-8884325a-e350-4f0f-bfd9-6aab48ffe585 e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:10:47.433 38 ERROR keystone.server.flask.application 
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application [None req-21e50c88-3d56-41c3-b4d7-d7eccca08d1e e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-15 21:11:02.400 38 ERROR keystone.server.flask.application 
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application [None req-c7994a26-13de-4822-8de3-c342efa8bd46 e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-02-15 21:11:03.726 38 ERROR keystone.server.flask.application 
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application [None req-3fb063e7-0661-4a96-b8d9-2bd230f92c4d e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:11:04.536 40 ERROR keystone.server.flask.application 
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application [None req-c5c6b8f4-1b77-4d53-a0f9-6b909789cd30 e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-15 21:11:14.462 39 ERROR keystone.server.flask.application 
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application [None req-35269614-637d-4bd8-89dd-3f33bdb9b40d e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-02-15 21:11:15.459 39 ERROR keystone.server.flask.application 
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application [None req-e85c2549-0aa8-4505-9a82-7b6d584da19f e8332fea0d0f4bccbe63e150e127b1d9 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     with Lock(
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self._enter()
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self.creator()
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     created_value = creator(
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-15 21:11:16.229 38 ERROR keystone.server.flask.application 
