2023-04-25 06:53:43.403 24 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-25 06:53:43.407 24 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-25 06:53:43.450 24 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-25 06:53:43.451 24 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-25 06:53:43.501 24 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-04-25 06:53:44.979 24 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-04-25 06:53:44.989 24 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-04-25 06:53:53.689 8 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-25 06:53:53.694 8 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-25 06:53:53.695 8 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-04-25 06:53:53.695 8 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-25 06:53:53.696 8 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-04-25 06:53:53.697 8 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-04-25 06:53:53.697 8 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-04-25 06:53:53.698 8 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-25 06:54:11.921 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created domain default
2023-04-25 06:54:12.021 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created project admin
2023-04-25 06:54:12.639 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created user admin
2023-04-25 06:54:12.663 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created role reader
2023-04-25 06:54:12.681 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created role member
2023-04-25 06:54:12.721 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created implied role where 2ef91e3774254e8b853f24d635dcdb7a implies 9d8107f55a7f466eb769c998596690a3
2023-04-25 06:54:12.736 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created role admin
2023-04-25 06:54:12.765 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created implied role where 0c9d0829e91f4249a14bf2be617d5e4c implies 2ef91e3774254e8b853f24d635dcdb7a
2023-04-25 06:54:12.784 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Granted role admin on project admin to user admin.
2023-04-25 06:54:12.797 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Granted role admin on the system to user admin.
2023-04-25 06:54:12.818 147 WARNING py.warnings [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-04-25 06:54:12.826 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created region RegionOne
2023-04-25 06:54:12.883 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created public endpoint http://169.16.1.147:5000
2023-04-25 06:54:12.896 147 INFO keystone.cmd.bootstrap [None req-5340b7c1-1165-4a55-9f1c-66d675fde404 - - - - - -] Created internal endpoint http://169.16.1.147:5000
2023-04-25 06:54:38.438 25 WARNING keystone.common.rbac_enforcer.enforcer [None req-c0adf6ff-1020-46ef-a322-dc134e42bd02 a145ff8b94944e1b873a391cb87d7373 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 06:54:39.257 27 WARNING keystone.common.rbac_enforcer.enforcer [None req-815dea82-f6d5-4966-8ff2-2403a7c0de97 a145ff8b94944e1b873a391cb87d7373 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 06:54:46.487 26 WARNING keystone.common.rbac_enforcer.enforcer [None req-8218638e-0d27-4b3b-be8f-3ebe8c3de84a a145ff8b94944e1b873a391cb87d7373 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application [None req-6072fccb-566e-4343-b9ec-3bd83d0a63bd a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:08.478 25 ERROR keystone.server.flask.application 
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application [None req-689c5873-6fa8-4ab8-a284-967d99dfd6e6 a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:17.647 26 ERROR keystone.server.flask.application 
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application [None req-ef2b6693-ce31-4058-b5a3-454eb808fa7a a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:56:32.853 26 ERROR keystone.server.flask.application 
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application [None req-7fdf2a27-025a-49cc-bbe6-b0aae3b146db a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-25 06:56:34.095 26 ERROR keystone.server.flask.application 
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application [None req-c4921930-ff9e-40af-b721-8b135bd492ee a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:34.968 27 ERROR keystone.server.flask.application 
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application [None req-09c3fb89-11a9-4bf1-bc72-0c057023bb1c a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:56:45.612 25 ERROR keystone.server.flask.application 
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application [None req-77acb0dc-e925-4ff9-8900-656cf62a89c5 a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-25 06:56:47.047 25 ERROR keystone.server.flask.application 
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application [None req-bdb610f0-88fa-4465-8ab7-6de245a51f2a a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:56:48.103 26 ERROR keystone.server.flask.application 
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application [None req-bc97d5b0-9f8e-4126-8672-503fdb02550f a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:59:39.568 26 ERROR keystone.server.flask.application 
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application [None req-71c74a2c-b35c-4f43-b8b5-04d08e6c2ce0 a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 06:59:53.583 25 ERROR keystone.server.flask.application 
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application [None req-6c973896-9807-483c-8a2d-c033f23c137d a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-25 06:59:54.731 25 ERROR keystone.server.flask.application 
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application [None req-76f139fc-654a-485e-b4c4-10fed64ce3b1 a145ff8b94944e1b873a391cb87d7373 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 06:59:55.416 27 ERROR keystone.server.flask.application 
