2023-04-24 18:37:59.932405 2023-04-24 18:37:59.930 38 WARNING keystone.common.rbac_enforcer.enforcer [None req-43c30c03-1469-42d9-94c3-5b5842c3d017 f261783d0c9f4570a0e35630997ea348 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-24 18:38:00.766409 2023-04-24 18:38:00.764 37 WARNING keystone.common.rbac_enforcer.enforcer [None req-c1514a3d-5719-4086-a886-8ac22be637eb f261783d0c9f4570a0e35630997ea348 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-24 18:38:08.905391 2023-04-24 18:38:08.903 39 WARNING keystone.common.rbac_enforcer.enforcer [None req-3f4866f3-cd63-46cf-886c-d9314c452c17 f261783d0c9f4570a0e35630997ea348 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-04-24 18:39:28.950699 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application [None req-6bafa76b-108f-4dd6-be54-bdab19bb7b54 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:28.950852 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:39:28.950881 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:39:28.950905 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:39:28.950924 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:39:28.950946 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:39:28.950983 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:39:28.951002 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:39:28.951035 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:39:28.951092 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:39:28.951122 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:39:28.951133 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:39:28.951143 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:39:28.951153 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:39:28.951163 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:39:28.951173 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:39:28.951182 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:39:28.951244 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:39:28.951255 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:39:28.951265 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:39:28.951295 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:39:28.951312 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:39:28.951321 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:39:28.951331 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:39:28.951341 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:39:28.951350 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:39:28.951359 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:39:28.951369 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:39:28.951378 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:39:28.951387 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:39:28.951397 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:39:28.951406 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:39:28.951415 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:39:28.951425 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:39:28.951434 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:39:28.951444 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:39:28.951454 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:39:28.951463 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:39:28.951473 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:28.951482 2023-04-24 18:39:28.925 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:39:38.852467 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application [None req-3e84d597-a063-4b9d-a8a2-6980fe3aedd2 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:38.852511 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:39:38.852562 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:39:38.852598 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:39:38.852608 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:39:38.852618 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:39:38.852627 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:39:38.852637 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:39:38.852647 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:39:38.852657 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:39:38.852667 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:39:38.852676 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:39:38.852686 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:39:38.852718 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:39:38.852727 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:39:38.852737 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:39:38.852747 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:39:38.852757 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:39:38.852766 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:39:38.852775 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:39:38.852785 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:39:38.852794 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:39:38.852803 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:39:38.852826 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:39:38.852837 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:39:38.852846 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:39:38.852883 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:39:38.852894 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:39:38.852904 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:39:38.852913 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:39:38.852922 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:39:38.852932 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:39:38.852941 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:39:38.852951 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:39:38.852960 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:39:38.852970 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:39:38.852979 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:39:38.852989 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:39:38.852998 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:38.853007 2023-04-24 18:39:38.839 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:39:55.535816 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application [None req-46482cc1-084f-49c5-87e2-7c90f46b9e58 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:39:55.535886 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:39:55.535899 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:39:55.535909 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:39:55.535919 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:39:55.535929 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:39:55.535939 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:39:55.535948 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:39:55.535958 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:39:55.535968 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:39:55.535978 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:39:55.536011 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:39:55.536023 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-24 18:39:55.536033 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-24 18:39:55.536042 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-24 18:39:55.536052 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-24 18:39:55.536062 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-24 18:39:55.536105 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-24 18:39:55.536116 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-24 18:39:55.536127 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-24 18:39:55.536136 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:39:55.536146 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:39:55.536156 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:39:55.536167 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:39:55.536177 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:39:55.536187 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:39:55.536197 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:39:55.536207 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:39:55.536217 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:39:55.536227 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:39:55.536237 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:39:55.536247 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:39:55.536256 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:39:55.536266 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:39:55.536305 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:39:55.536331 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:39:55.536342 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-24 18:39:55.536352 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-24 18:39:55.536361 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-24 18:39:55.536371 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-24 18:39:55.536381 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-24 18:39:55.536391 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-24 18:39:55.536400 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:39:55.536409 2023-04-24 18:39:55.527 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:39:56.759038 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application [None req-a2d43aee-9210-4c8e-a497-35737cce1f5f f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-24 18:39:56.759129 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:39:56.759143 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:39:56.759154 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:39:56.759164 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:39:56.759193 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:39:56.759205 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:39:56.759215 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:39:56.759240 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:39:56.759250 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:39:56.759289 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:39:56.759306 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:39:56.759316 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-24 18:39:56.759326 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-24 18:39:56.759335 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-24 18:39:56.759361 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-24 18:39:56.759373 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:39:56.759383 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:39:56.759393 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-24 18:39:56.759403 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:39:56.759412 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-24 18:39:56.759422 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:39:56.759432 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:39:56.759442 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:39:56.759452 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:39:56.759462 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:39:56.759472 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:39:56.759482 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:39:56.759497 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:39:56.759507 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:39:56.759517 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:39:56.759527 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:39:56.759537 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:39:56.759548 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:39:56.759558 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:39:56.759568 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:39:56.759577 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-24 18:39:56.759587 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-24 18:39:56.759597 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-24 18:39:56.759607 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-24 18:39:56.759628 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-24 18:39:56.759639 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-24 18:39:56.759649 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-24 18:39:56.759666 2023-04-24 18:39:56.752 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:39:57.644647 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application [None req-4cb97aff-43d1-41d2-8cb1-7f9a831a7cda f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:57.644705 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:39:57.644728 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:39:57.644749 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:39:57.644766 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:39:57.644785 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:39:57.644802 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:39:57.644820 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:39:57.644849 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:39:57.644879 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:39:57.644901 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:39:57.644920 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:39:57.644938 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:39:57.644962 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:39:57.644982 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:39:57.645002 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:39:57.645019 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:39:57.645039 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:39:57.645056 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:39:57.645122 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:39:57.645220 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:39:57.645253 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:39:57.645293 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:39:57.645318 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:39:57.645335 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:39:57.645352 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:39:57.645369 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:39:57.645392 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:39:57.645412 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:39:57.645429 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:39:57.645447 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:39:57.645467 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:39:57.645483 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:39:57.645503 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:39:57.645522 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:39:57.645543 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:39:57.645559 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:39:57.645576 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:39:57.645593 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:39:57.645611 2023-04-24 18:39:57.626 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:40:08.914998 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application [None req-3fb6716e-84b8-4b29-981f-b5b903663958 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:40:08.915088 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:40:08.915107 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:40:08.915118 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:40:08.915128 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:40:08.915161 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:40:08.915173 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:40:08.915183 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:40:08.915199 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:40:08.915210 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:40:08.915220 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:40:08.915230 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:40:08.915240 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-24 18:40:08.915249 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-24 18:40:08.915259 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-24 18:40:08.915268 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-24 18:40:08.915319 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-24 18:40:08.915329 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-24 18:40:08.915352 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-24 18:40:08.915369 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-24 18:40:08.915379 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:40:08.915389 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:40:08.915398 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:40:08.915408 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:40:08.915417 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:40:08.915427 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:40:08.915436 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:40:08.915446 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:40:08.915475 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:40:08.915487 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:40:08.915496 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:40:08.915506 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:40:08.915516 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:40:08.915525 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:40:08.915536 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:40:08.915545 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:40:08.915556 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-24 18:40:08.915567 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-24 18:40:08.915576 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-24 18:40:08.915586 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-24 18:40:08.915596 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-24 18:40:08.915606 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-24 18:40:08.915615 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:40:08.915625 2023-04-24 18:40:08.906 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:40:10.134339 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application [None req-c47d3e74-a7c0-4f2d-ad23-aed15f64ec63 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-24 18:40:10.134469 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:40:10.134482 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:40:10.134493 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:40:10.134502 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:40:10.134513 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:40:10.134523 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:40:10.134533 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:40:10.134572 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:40:10.134606 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:40:10.134626 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:40:10.134636 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:40:10.134646 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-24 18:40:10.134656 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-24 18:40:10.134665 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-24 18:40:10.134675 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-24 18:40:10.134685 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:40:10.134695 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:40:10.134704 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-24 18:40:10.134714 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:40:10.134723 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-24 18:40:10.134733 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:40:10.134742 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:40:10.134752 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:40:10.134762 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:40:10.134772 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:40:10.134782 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:40:10.134791 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:40:10.134801 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:40:10.134810 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:40:10.134820 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:40:10.134829 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:40:10.134839 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:40:10.134859 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:40:10.134870 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:40:10.134880 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:40:10.134889 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-24 18:40:10.134899 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-24 18:40:10.134908 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-24 18:40:10.134918 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-24 18:40:10.134928 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-24 18:40:10.134938 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-24 18:40:10.134947 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-24 18:40:10.134957 2023-04-24 18:40:10.128 38 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:40:11.015429 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application [None req-2a1b79d7-72f2-4b17-8b11-27bd7d61ffd1 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:40:11.015475 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:40:11.015487 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:40:11.015498 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:40:11.015523 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:40:11.015533 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:40:11.015543 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:40:11.015553 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:40:11.015563 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:40:11.015574 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:40:11.015591 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:40:11.015609 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:40:11.015626 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:40:11.015671 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:40:11.015715 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:40:11.015744 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:40:11.015765 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:40:11.015783 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:40:11.015815 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:40:11.015883 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:40:11.015922 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:40:11.015940 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:40:11.015957 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:40:11.015977 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:40:11.015995 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:40:11.016013 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:40:11.016039 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:40:11.016059 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:40:11.016132 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:40:11.016152 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:40:11.016171 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:40:11.016187 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:40:11.016199 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:40:11.016209 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:40:11.016219 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:40:11.016229 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:40:11.016238 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:40:11.016248 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:40:11.016305 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:40:11.016334 2023-04-24 18:40:11.011 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:43:12.742053 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application [None req-756d7ca3-2516-4772-b56c-1fe9b664a4fa f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:43:12.743516 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:43:12.743530 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:43:12.743540 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:43:12.743554 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:43:12.743572 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:43:12.743582 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:43:12.743592 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:43:12.743606 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:43:12.743616 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:43:12.743625 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:43:12.743635 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:43:12.743644 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:43:12.743654 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:43:12.743664 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:43:12.743673 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:43:12.743683 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:43:12.743692 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:43:12.743701 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:43:12.743711 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:43:12.743721 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:43:12.743730 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:43:12.743764 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:43:12.743775 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:43:12.743785 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:43:12.743795 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:43:12.743804 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:43:12.743813 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:43:12.743823 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:43:12.743833 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:43:12.743842 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:43:12.743852 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:43:12.743861 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:43:12.743871 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:43:12.743880 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:43:12.743891 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:43:12.743900 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:43:12.743910 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:43:12.743920 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:43:12.743929 2023-04-24 18:43:12.737 39 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:43:27.616114 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application [None req-d80aae26-b912-4c69-896d-81aafbb60ec4 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:43:27.616160 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:43:27.616172 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:43:27.616183 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:43:27.616192 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:43:27.616203 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:43:27.616212 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:43:27.616299 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:43:27.616313 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:43:27.616323 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:43:27.616333 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:43:27.616343 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:43:27.616353 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-24 18:43:27.616362 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-24 18:43:27.616372 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-24 18:43:27.616382 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-24 18:43:27.616392 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-24 18:43:27.616402 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-24 18:43:27.616412 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-24 18:43:27.616422 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-24 18:43:27.616432 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:43:27.616442 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:43:27.616452 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:43:27.616461 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:43:27.616471 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:43:27.616481 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:43:27.616490 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:43:27.616505 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:43:27.616514 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:43:27.616524 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:43:27.616534 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:43:27.616578 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:43:27.616590 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:43:27.616600 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:43:27.616610 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:43:27.616620 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:43:27.616629 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-24 18:43:27.616639 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-24 18:43:27.616649 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-24 18:43:27.616658 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-24 18:43:27.616668 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-24 18:43:27.616678 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-24 18:43:27.616688 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-24 18:43:27.616698 2023-04-24 18:43:27.610 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:43:28.997064 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application [None req-3c23f915-cb00-4fdb-bb12-331c085831c3 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-24 18:43:28.997149 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:43:28.997168 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:43:28.997185 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:43:28.997196 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:43:28.997208 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:43:28.997225 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:43:28.997241 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:43:28.997281 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:43:28.997301 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:43:28.997322 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:43:28.997367 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:43:28.997383 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-24 18:43:28.997397 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-24 18:43:28.997414 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-24 18:43:28.997430 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-24 18:43:28.997440 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:43:28.997451 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:43:28.997467 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-24 18:43:28.997484 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:43:28.997494 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-24 18:43:28.997504 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-24 18:43:28.997516 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:43:28.997541 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:43:28.997559 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:43:28.997572 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:43:28.997588 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:43:28.997606 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:43:28.997617 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:43:28.997627 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:43:28.997639 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:43:28.997657 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:43:28.997673 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:43:28.997683 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:43:28.997692 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:43:28.997707 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:43:28.997740 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-24 18:43:28.997753 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-24 18:43:28.997767 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-24 18:43:28.997785 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-24 18:43:28.997800 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-24 18:43:28.997810 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-24 18:43:28.997821 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-24 18:43:28.997837 2023-04-24 18:43:28.989 37 ERROR keystone.server.flask.application \x1b[00m
2023-04-24 18:43:29.738842 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application [None req-9d16c8ea-f0d9-4e18-9704-460e7d6ce3a4 f261783d0c9f4570a0e35630997ea348 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:43:29.738887 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-24 18:43:29.738898 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-24 18:43:29.738908 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-24 18:43:29.738918 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-24 18:43:29.738928 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-24 18:43:29.738943 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-24 18:43:29.738975 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-24 18:43:29.738984 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-24 18:43:29.738994 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-24 18:43:29.739004 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-24 18:43:29.739013 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-24 18:43:29.739022 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-24 18:43:29.739032 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-24 18:43:29.739041 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-24 18:43:29.739050 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-24 18:43:29.739127 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-24 18:43:29.739142 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-24 18:43:29.739152 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-24 18:43:29.739161 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-24 18:43:29.739171 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-24 18:43:29.739180 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-24 18:43:29.739190 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-24 18:43:29.739199 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     with Lock(
2023-04-24 18:43:29.739209 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-24 18:43:29.739218 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self._enter()
2023-04-24 18:43:29.739227 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-24 18:43:29.739237 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-24 18:43:29.739264 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-24 18:43:29.739277 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self.creator()
2023-04-24 18:43:29.739287 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-24 18:43:29.739296 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     created_value = creator(
2023-04-24 18:43:29.739305 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-24 18:43:29.739314 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-24 18:43:29.739323 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-24 18:43:29.739333 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-24 18:43:29.739342 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-24 18:43:29.739352 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-24 18:43:29.739361 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-24 18:43:29.739370 2023-04-24 18:43:29.735 38 ERROR keystone.server.flask.application \x1b[00m
