2023-04-12 03:48:29.315 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-12 03:48:29.317 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-12 03:48:29.358 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-12 03:48:29.359 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-12 03:48:29.411 23 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-04-12 03:48:30.786 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-04-12 03:48:30.806 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-04-12 03:48:39.928 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-12 03:48:39.933 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-12 03:48:39.933 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-04-12 03:48:39.934 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-12 03:48:39.935 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-04-12 03:48:39.936 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-04-12 03:48:39.936 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-04-12 03:48:39.937 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-12 03:48:58.915 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created domain default
2023-04-12 03:48:59.003 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created project admin
2023-04-12 03:48:59.641 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created user admin
2023-04-12 03:48:59.666 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created role reader
2023-04-12 03:48:59.687 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created role member
2023-04-12 03:48:59.729 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created implied role where e8ffd945c25d4270b7a4dfc15a1b39b1 implies 06a42fa16d624c93b406fdf025f904a4
2023-04-12 03:48:59.745 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created role admin
2023-04-12 03:48:59.777 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created implied role where 8b64f462a1414d3e9557573e660a0200 implies e8ffd945c25d4270b7a4dfc15a1b39b1
2023-04-12 03:48:59.799 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Granted role admin on project admin to user admin.
2023-04-12 03:48:59.810 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Granted role admin on the system to user admin.
2023-04-12 03:48:59.834 148 WARNING py.warnings [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-04-12 03:48:59.842 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created region RegionOne
2023-04-12 03:48:59.896 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created public endpoint http://169.16.1.179:5000
2023-04-12 03:48:59.916 148 INFO keystone.cmd.bootstrap [None req-eb9eb5de-2c32-49be-bcc4-331c0f93f0c4 - - - - - -] Created internal endpoint http://169.16.1.179:5000
2023-04-12 03:49:26.493 27 WARNING keystone.common.rbac_enforcer.enforcer [None req-9fd4aa27-5012-4466-aedd-0af78f1d9495 9e602769eab048e7982837fdee543037 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-12 03:49:27.335 28 WARNING keystone.common.rbac_enforcer.enforcer [None req-5ee3317e-6ece-4d73-a89b-41d804070abb 9e602769eab048e7982837fdee543037 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-12 03:49:35.394 26 WARNING keystone.common.rbac_enforcer.enforcer [None req-6afc2478-bff4-4a14-8a6c-3de2bec6625e 9e602769eab048e7982837fdee543037 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application [None req-e1f1e947-ab4b-4066-b2e9-7db6756d785b 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:50:52.587 27 ERROR keystone.server.flask.application 
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application [None req-067b04b0-0772-434e-831c-634a2279f28e 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:01.316 26 ERROR keystone.server.flask.application 
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application [None req-2503ede8-bcb8-450a-928c-6459c66c4e61 9e602769eab048e7982837fdee543037 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:51:16.479 26 ERROR keystone.server.flask.application 
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application [None req-ea482aa3-9f94-42e0-8e29-aa17cd8d1541 9e602769eab048e7982837fdee543037 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-12 03:51:17.638 26 ERROR keystone.server.flask.application 
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application [None req-7c87fe16-4ce5-4af4-8757-50bad04a71bf 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:18.542 28 ERROR keystone.server.flask.application 
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application [None req-3ed5ac9e-eec2-41b1-ae52-c564a00430c7 9e602769eab048e7982837fdee543037 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:51:28.318 27 ERROR keystone.server.flask.application 
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application [None req-2b2a08be-eac9-45b1-9ea5-3e4882608be7 9e602769eab048e7982837fdee543037 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-12 03:51:29.759 28 ERROR keystone.server.flask.application 
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application [None req-debbfa14-f5dc-4825-b06a-9457e0712c3b 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:51:30.611 26 ERROR keystone.server.flask.application 
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application [None req-b405ce1a-3a39-462e-bda5-e938fcb07d2c 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:54:28.129 26 ERROR keystone.server.flask.application 
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application [None req-6291a2ff-8d28-46eb-9598-152ad452c8bc 9e602769eab048e7982837fdee543037 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-12 03:54:44.149 27 ERROR keystone.server.flask.application 
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application [None req-0a93d777-e6d1-4b3b-8705-37a0480c4755 9e602769eab048e7982837fdee543037 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-12 03:54:45.468 27 ERROR keystone.server.flask.application 
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application [None req-5dee0ee9-0f20-4464-b736-fed02cb9206c 9e602769eab048e7982837fdee543037 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     with Lock(
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-12 03:54:46.296 28 ERROR keystone.server.flask.application 
