2023-03-14 22:09:03.297 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-03-14 22:09:03.299 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-03-14 22:09:03.338 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-03-14 22:09:03.339 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-03-14 22:09:03.379 23 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-03-14 22:09:04.521 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-03-14 22:09:04.532 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-03-14 22:09:13.364 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-03-14 22:09:13.369 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-03-14 22:09:13.371 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-03-14 22:09:13.373 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-03-14 22:09:13.373 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-03-14 22:09:13.374 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-03-14 22:09:13.375 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-03-14 22:09:13.376 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-03-14 22:09:32.212 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created domain default
2023-03-14 22:09:32.312 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created project admin
2023-03-14 22:09:33.022 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created user admin
2023-03-14 22:09:33.041 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created role reader
2023-03-14 22:09:33.057 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created role member
2023-03-14 22:09:33.091 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created implied role where 385ccaec37eb47aca8ba424a8e36a71b implies 1ca3559efe0d4655829c43afd726792f
2023-03-14 22:09:33.106 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created role admin
2023-03-14 22:09:33.131 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created implied role where cac832c1bcc94e69aa9eccf4b0bf41c1 implies 385ccaec37eb47aca8ba424a8e36a71b
2023-03-14 22:09:33.147 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Granted role admin on project admin to user admin.
2023-03-14 22:09:33.156 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Granted role admin on the system to user admin.
2023-03-14 22:09:33.173 149 WARNING py.warnings [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-03-14 22:09:33.180 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created region RegionOne
2023-03-14 22:09:33.230 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created public endpoint http://169.16.1.174:5000
2023-03-14 22:09:33.243 149 INFO keystone.cmd.bootstrap [None req-791fdbe1-77f0-4679-b211-4db1d69442e9 - - - - - -] Created internal endpoint http://169.16.1.174:5000
2023-03-14 22:09:58.386 28 WARNING keystone.common.rbac_enforcer.enforcer [None req-ed1a5a3f-953a-4a8d-b768-4e16b987550c 70e01db0b300404ea3d08f7211c654b6 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-14 22:09:59.306 27 WARNING keystone.common.rbac_enforcer.enforcer [None req-01bd7fa3-7686-415c-ad5a-51f3c0e97b54 70e01db0b300404ea3d08f7211c654b6 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-14 22:10:06.625 26 WARNING keystone.common.rbac_enforcer.enforcer [None req-cf8543cc-7d98-420b-9887-57ec1940963c 70e01db0b300404ea3d08f7211c654b6 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application [None req-be5f4a83-cbdb-4b98-a2ac-4741a088715b 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:26.670 28 ERROR keystone.server.flask.application 
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application [None req-4a2bb597-8c79-4e31-8869-fcae8f6e38d4 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:36.610 27 ERROR keystone.server.flask.application 
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application [None req-ab9cb631-dad9-4353-b9c2-3070c4d6b641 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:11:52.524 27 ERROR keystone.server.flask.application 
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application [None req-1635fd4f-96d6-4f20-b125-d97bf3045cbf 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-14 22:11:54.082 27 ERROR keystone.server.flask.application 
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application [None req-4e133ed2-ae6a-44e5-92d7-3cf670cff335 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:11:55.081 26 ERROR keystone.server.flask.application 
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application [None req-cdf38ab7-435d-4aec-b54d-362e070ccb5c 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:12:04.999 28 ERROR keystone.server.flask.application 
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application [None req-0235b554-3704-41c3-a3bf-913646a9ea2d 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-14 22:12:06.347 28 ERROR keystone.server.flask.application 
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application [None req-e3467bae-058b-48fd-8791-d50355196388 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:12:07.378 27 ERROR keystone.server.flask.application 
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application [None req-e0dd3346-a8ff-4ce8-9328-eba72353b909 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:15:19.446 28 ERROR keystone.server.flask.application 
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application [None req-da4abf21-7e00-434d-9bfd-f4e89db90428 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-14 22:15:34.938 26 ERROR keystone.server.flask.application 
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application [None req-3e49197e-acc0-43f5-a85f-af9bec28d2d6 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-14 22:15:36.356 26 ERROR keystone.server.flask.application 
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application [None req-bdfdc213-ec23-475b-8346-9fee822c7c19 70e01db0b300404ea3d08f7211c654b6 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     with Lock(
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self._enter()
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self.creator()
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     created_value = creator(
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-14 22:15:37.294 27 ERROR keystone.server.flask.application 
