2023-02-24 10:05:08.629 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-02-24 10:05:08.632 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-02-24 10:05:08.703 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-02-24 10:05:08.704 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-02-24 10:05:08.773 23 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-02-24 10:05:10.093 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-02-24 10:05:10.106 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-02-24 10:05:19.212 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-02-24 10:05:19.216 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-02-24 10:05:19.218 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-02-24 10:05:19.219 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-02-24 10:05:19.219 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-02-24 10:05:19.221 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-02-24 10:05:19.221 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-02-24 10:05:19.222 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-02-24 10:05:37.528 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created domain default
2023-02-24 10:05:37.623 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created project admin
2023-02-24 10:05:38.312 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created user admin
2023-02-24 10:05:38.332 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created role reader
2023-02-24 10:05:38.349 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created role member
2023-02-24 10:05:38.383 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created implied role where d9715b52dec4466d81b5b1550bb5bde5 implies 1c34f6ff666142359f90638bb48ea808
2023-02-24 10:05:38.395 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created role admin
2023-02-24 10:05:38.420 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created implied role where 19043054315f44bca21e5b1c5090b1af implies d9715b52dec4466d81b5b1550bb5bde5
2023-02-24 10:05:38.437 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Granted role admin on project admin to user admin.
2023-02-24 10:05:38.449 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Granted role admin on the system to user admin.
2023-02-24 10:05:38.520 149 WARNING py.warnings [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-02-24 10:05:38.532 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created region RegionOne
2023-02-24 10:05:38.620 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created public endpoint http://169.16.1.176:5000
2023-02-24 10:05:38.645 149 INFO keystone.cmd.bootstrap [None req-ce84e306-888c-4731-a8b4-3b9eb52ad947 - - - - - -] Created internal endpoint http://169.16.1.176:5000
2023-02-24 10:06:07.451 27 WARNING keystone.common.rbac_enforcer.enforcer [None req-f48c6e9f-af74-4536-8fa1-f977f13fc0e7 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-24 10:06:08.381 28 WARNING keystone.common.rbac_enforcer.enforcer [None req-36925bae-76d3-4f05-a1a3-a909aef28514 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-24 10:06:16.727 29 WARNING keystone.common.rbac_enforcer.enforcer [None req-c202febe-b95b-47f8-aaf2-af45180d99cc e7f72c8596b545dbbc9e6232011cc803 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application [None req-6205cdcf-7716-4624-8d84-7f7dcaa96ff1 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:07:38.372 27 ERROR keystone.server.flask.application 
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application [None req-15f5a0bd-7882-4f31-8498-484c8c70621f e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:07:48.623 29 ERROR keystone.server.flask.application 
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application [None req-d5b7dfb0-e639-417f-a5c5-7c498c634d3f e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:08:03.926 29 ERROR keystone.server.flask.application 
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application [None req-d2df83eb-4e47-4e10-a5be-14db94989d3c e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-02-24 10:08:05.546 29 ERROR keystone.server.flask.application 
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application [None req-5581e7af-1fc1-4c1f-bf87-e7a1f1b0a2f7 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:08:06.571 28 ERROR keystone.server.flask.application 
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application [None req-3765ff24-240b-49e8-8d6e-f0ab17d9d13a e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:08:16.774 27 ERROR keystone.server.flask.application 
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application [None req-681da77f-d216-4bd2-9c8b-e2cebbe7df55 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-02-24 10:08:18.239 27 ERROR keystone.server.flask.application 
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application [None req-d3727159-f45e-4cba-97c0-c0ccb4c14578 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:08:19.195 29 ERROR keystone.server.flask.application 
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application [None req-13cee9e0-ac2a-4051-9d76-dbed8081f7e9 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:11:22.575 29 ERROR keystone.server.flask.application 
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application [None req-e9da5114-023b-40c3-ab80-263b1b50b4e3 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-02-24 10:11:37.901 27 ERROR keystone.server.flask.application 
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application [None req-e161da15-88b4-4ea8-b110-dfd3eb043a60 e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-02-24 10:11:39.182 27 ERROR keystone.server.flask.application 
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application [None req-6dd5e381-de3f-4212-8b4b-8c8d53b1ec3a e7f72c8596b545dbbc9e6232011cc803 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     with Lock(
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self._enter()
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self.creator()
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     created_value = creator(
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-02-24 10:11:40.031 28 ERROR keystone.server.flask.application 
2023-02-24 10:19:15.202 28 WARNING py.warnings [None req-5e1c912c-f9b2-44e4-bdf6-073c95829a55 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_domains": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:15.416 27 WARNING py.warnings [None req-42092331-c801-41aa-bcf7-18c505c630b0 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_project": "(role:admin and system_scope:all) or (role:admin and domain_id:%(target.project.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:15.695 29 WARNING py.warnings [None req-58c1f32e-503d-4bed-8f87-ce52f8b2b85b e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_user": "(role:admin and system_scope:all) or (role:admin and token.domain.id:%(target.user.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:16.507 28 WARNING py.warnings [None req-7a90a40e-1f39-467a-b8c9-6e6208d89ceb e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:16.778 27 WARNING py.warnings [None req-8d9d9f45-a980-43c9-a5d5-4b73911d9dda e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:17.064 29 WARNING py.warnings [None req-2b40a5dc-3ccd-4625-af2e-9b889b987406 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:19.951 27 WARNING py.warnings [None req-231ee468-9d1d-4df9-bddb-160013ed19c8 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:20.206 29 WARNING py.warnings [None req-a615aa1c-1515-4ce1-aa84-7f765497a123 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:20.467 28 WARNING py.warnings [None req-73e118bf-4552-4883-880d-df3bb85884c2 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

2023-02-24 10:19:22.753 28 WARNING py.warnings [None req-50180ff2-22ca-434e-980f-fda323b40877 e7f72c8596b545dbbc9e6232011cc803 e6f844d7c13d4fae8b0b454c19da4ec2 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_system_grant_for_user": "role:admin and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
  warnings.warn(msg)

