2023-03-07 21:44:14.658030 2023-03-07 21:44:14.656 39 WARNING keystone.common.rbac_enforcer.enforcer [None req-edd4f95d-4717-4a50-845b-3528c0536d31 9686372be73d4d269440f3838c70b399 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-03-07 21:44:15.525829 2023-03-07 21:44:15.523 38 WARNING keystone.common.rbac_enforcer.enforcer [None req-83a1e1d9-5b42-4d05-bfc3-11c8ee3f12a3 9686372be73d4d269440f3838c70b399 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-03-07 21:44:23.885622 2023-03-07 21:44:23.884 37 WARNING keystone.common.rbac_enforcer.enforcer [None req-d46ab7de-d1a5-4f7a-8a70-47b85bb8baf3 9686372be73d4d269440f3838c70b399 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.\x1b[00m
2023-03-07 21:45:41.747216 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application [None req-48646c96-5d50-42b0-adc5-8a17f76cbf3e 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:45:41.747290 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:45:41.747303 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:45:41.747313 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:45:41.747323 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:45:41.747333 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:45:41.747366 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:45:41.747376 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:45:41.747406 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:45:41.747419 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:45:41.747429 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:45:41.747439 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:45:41.747448 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:45:41.747458 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:45:41.747467 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:45:41.747477 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:45:41.747486 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:45:41.747531 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:45:41.747543 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:45:41.747553 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:45:41.747568 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:45:41.747580 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:45:41.747590 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:45:41.747600 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:45:41.747609 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:45:41.747619 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:45:41.747628 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:45:41.747638 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:45:41.747654 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:45:41.747666 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:45:41.747675 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:45:41.747685 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:45:41.747694 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:45:41.747720 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:45:41.747731 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:45:41.747740 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:45:41.747750 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:45:41.747760 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:45:41.747769 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:45:41.747778 2023-03-07 21:45:41.636 39 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:45:51.379102 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application [None req-a96e74b2-4eca-4bd9-af6c-e92904067ba2 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:45:51.379145 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:45:51.379202 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:45:51.379218 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:45:51.379228 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:45:51.379239 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:45:51.379248 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:45:51.379258 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:45:51.379275 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:45:51.379293 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:45:51.379307 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:45:51.379317 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:45:51.379327 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:45:51.379337 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:45:51.379347 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:45:51.379357 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:45:51.379367 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:45:51.379377 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:45:51.379386 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:45:51.379396 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:45:51.379406 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:45:51.379417 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:45:51.379426 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:45:51.379437 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:45:51.379446 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:45:51.379456 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:45:51.379485 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:45:51.379498 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:45:51.379508 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:45:51.379518 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:45:51.379528 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:45:51.379538 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:45:51.379547 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:45:51.379557 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:45:51.379567 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:45:51.379578 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:45:51.379588 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:45:51.379598 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:45:51.379608 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:45:51.379618 2023-03-07 21:45:51.367 37 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:06.300036 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application [None req-70f16669-10aa-483e-8528-d7b6cabc30f0 9686372be73d4d269440f3838c70b399 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:46:06.300129 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:06.300196 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:06.300232 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:06.300259 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:06.300283 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:06.300307 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:06.300334 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:06.300378 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:06.300422 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:06.300448 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:06.300516 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:06.300543 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:46:06.300569 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:46:06.300590 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:46:06.300613 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:46:06.300638 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:46:06.300660 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:46:06.300722 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:46:06.300756 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:46:06.300780 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:06.300805 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:06.300830 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:06.300851 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:06.300877 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:06.300898 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:06.300921 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:06.300948 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:06.300967 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:06.300992 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:06.301016 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:06.301059 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:06.301084 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:06.301112 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:06.301132 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:06.301238 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:06.301271 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:46:06.301297 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:46:06.301322 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:46:06.301341 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:46:06.301366 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:46:06.301389 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:46:06.301402 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:46:06.301420 2023-03-07 21:46:06.287 37 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:07.596368 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application [None req-0de7207e-163a-41a8-9fc0-f91faaad36db 9686372be73d4d269440f3838c70b399 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-07 21:46:07.596421 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:07.596443 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:07.596476 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:07.596498 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:07.596512 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:07.596541 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:07.596562 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:07.596586 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:07.596603 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:07.596614 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:07.596633 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:07.596655 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:46:07.596671 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:46:07.596720 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:46:07.596790 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:46:07.596813 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:07.596836 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:07.596853 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:46:07.596870 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:46:07.596892 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:46:07.596910 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:46:07.596924 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:07.596945 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:07.597006 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:07.597021 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:07.597041 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:07.597064 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:07.597084 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:07.597097 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:07.597110 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:07.597132 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:07.597152 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:07.597199 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:07.597224 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:07.597245 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:07.597266 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:46:07.597282 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:46:07.597292 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:46:07.597302 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:46:07.597352 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:46:07.597379 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:46:07.597396 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-03-07 21:46:07.597407 2023-03-07 21:46:07.587 37 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:08.371426 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application [None req-ffb8357e-c24e-4eeb-8ffd-51880f7f98c8 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:46:08.371471 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:08.371483 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:08.371495 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:08.371505 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:08.371517 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:08.371528 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:08.371538 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:08.371557 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:08.371571 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:08.371582 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:08.371593 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:08.371603 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:46:08.371614 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:46:08.371625 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:46:08.371635 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:46:08.371646 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:08.371657 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:08.371667 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:08.371677 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:08.371744 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:08.371762 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:08.371772 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:08.371784 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:08.371795 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:08.371805 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:08.371816 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:08.371827 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:08.371837 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:08.371848 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:08.371859 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:08.371870 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:08.371880 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:46:08.371891 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:46:08.371901 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:46:08.371912 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:46:08.371923 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:46:08.371933 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:46:08.371944 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:46:08.371954 2023-03-07 21:46:08.361 38 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:17.654427 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application [None req-8adb49d2-a9b5-4270-8d4c-611ed2a3c92a 9686372be73d4d269440f3838c70b399 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:46:17.654503 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:17.654516 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:17.654527 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:17.654537 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:17.654561 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:17.654572 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:17.654583 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:17.654601 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:17.654615 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:17.654625 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:17.654636 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:17.654646 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:46:17.654656 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:46:17.654666 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:46:17.654676 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:46:17.654725 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:46:17.654740 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:46:17.654760 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:46:17.654773 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:46:17.654783 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:17.654794 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:17.654804 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:17.654814 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:17.654825 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:17.654835 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:17.654845 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:17.654856 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:17.654878 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:17.654890 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:17.654900 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:17.654911 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:17.654921 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:17.654931 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:17.654941 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:17.654951 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:17.654961 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:46:17.654971 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:46:17.654981 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:46:17.654991 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:46:17.655001 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:46:17.655012 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:46:17.655021 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:46:17.655031 2023-03-07 21:46:17.648 39 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:18.972518 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application [None req-2c6b1765-b406-4950-b63f-9f5048b028b1 9686372be73d4d269440f3838c70b399 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-07 21:46:18.972586 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:18.972600 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:18.972610 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:18.972619 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:18.972630 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:18.972654 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:18.972664 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:18.972674 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:18.972747 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:18.972761 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:18.972771 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:18.972780 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:46:18.972790 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:46:18.972799 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:46:18.972810 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:46:18.972819 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:18.972829 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:18.972839 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:46:18.972848 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:46:18.972858 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:46:18.972868 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:46:18.972877 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:18.972887 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:18.972897 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:18.972907 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:18.972917 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:18.972927 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:18.972936 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:18.972946 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:18.972955 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:18.972965 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:18.972975 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:18.973004 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:18.973016 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:18.973026 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:18.973036 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:46:18.973046 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:46:18.973055 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:46:18.973065 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:46:18.973075 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:46:18.973085 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:46:18.973094 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-03-07 21:46:18.973104 2023-03-07 21:46:18.967 39 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:46:19.691498 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application [None req-ac6e8612-4b20-4432-a0a5-f1e210ec4668 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:46:19.691688 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:46:19.691733 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:46:19.691745 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:46:19.691754 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:46:19.691764 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:46:19.691774 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:46:19.691784 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:46:19.691794 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:46:19.691804 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:46:19.691814 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:46:19.691824 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:46:19.691834 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:46:19.691860 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:46:19.691872 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:46:19.691882 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:46:19.691891 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:46:19.691901 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:46:19.691911 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:46:19.691921 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:46:19.691931 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:46:19.691941 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:46:19.691951 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:46:19.691961 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:46:19.691974 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:46:19.691987 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:46:19.691997 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:46:19.692006 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:46:19.692016 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:46:19.692026 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:46:19.692036 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:46:19.692046 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:46:19.692055 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:46:19.692065 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:46:19.692075 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:46:19.692085 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:46:19.692095 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:46:19.692105 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:46:19.692125 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:46:19.692136 2023-03-07 21:46:19.688 37 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:49:11.397073 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application [None req-49dfb1a8-9e25-4eb5-8329-10fa129105df 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:49:11.397143 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:49:11.397156 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:49:11.397205 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:49:11.397220 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:49:11.397236 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:49:11.397246 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:49:11.397256 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:49:11.397266 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:49:11.397276 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:49:11.397286 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:49:11.397296 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:49:11.397306 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:49:11.397316 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:49:11.397326 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:49:11.397336 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:49:11.397346 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:49:11.397356 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:49:11.397366 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:49:11.397376 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:49:11.397386 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:49:11.397396 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:49:11.397433 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:49:11.397446 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:49:11.397456 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:49:11.397466 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:49:11.397476 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:49:11.397485 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:49:11.397495 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:49:11.397505 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:49:11.397515 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:49:11.397525 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:49:11.397534 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:49:11.397544 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:49:11.397554 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:49:11.397564 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:49:11.397573 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:49:11.397583 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:49:11.397593 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:49:11.397603 2023-03-07 21:49:11.394 37 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:49:26.199080 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application [None req-9467cda6-52bc-4f2e-a3ab-682f2b6f4067 9686372be73d4d269440f3838c70b399 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:49:26.199130 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:49:26.199142 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:49:26.199152 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:49:26.199197 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:49:26.199215 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:49:26.199232 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:49:26.199285 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:49:26.199305 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:49:26.199318 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:49:26.199332 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:49:26.199346 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:49:26.199356 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-03-07 21:49:26.199366 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-03-07 21:49:26.199375 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-03-07 21:49:26.199385 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-03-07 21:49:26.199403 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-03-07 21:49:26.199416 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-03-07 21:49:26.199431 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-03-07 21:49:26.199444 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-03-07 21:49:26.199454 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:49:26.199464 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:49:26.199474 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:49:26.199484 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:49:26.199494 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:49:26.199504 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:49:26.199513 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:49:26.199524 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:49:26.199534 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:49:26.199544 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:49:26.199553 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:49:26.199585 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:49:26.199598 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:49:26.199608 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:49:26.199618 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:49:26.199628 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:49:26.199638 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-03-07 21:49:26.199648 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-03-07 21:49:26.199658 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-03-07 21:49:26.199699 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-03-07 21:49:26.199716 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-03-07 21:49:26.199726 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-03-07 21:49:26.199736 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-03-07 21:49:26.199745 2023-03-07 21:49:26.194 39 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:49:27.592271 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application [None req-0a7705b5-b18e-4e7d-b3a4-f60c6f02a88e 9686372be73d4d269440f3838c70b399 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-07 21:49:27.592352 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:49:27.592366 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:49:27.592377 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:49:27.592387 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:49:27.592397 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:49:27.592407 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:49:27.592417 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:49:27.592427 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:49:27.592437 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:49:27.592447 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:49:27.592476 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:49:27.592488 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-03-07 21:49:27.592498 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-03-07 21:49:27.592507 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-03-07 21:49:27.592517 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-03-07 21:49:27.592527 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:49:27.592537 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:49:27.592546 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-03-07 21:49:27.592556 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:49:27.592566 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-03-07 21:49:27.592575 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-03-07 21:49:27.592585 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:49:27.592595 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:49:27.592605 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:49:27.592615 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:49:27.592624 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:49:27.592634 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:49:27.592644 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:49:27.592653 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:49:27.592663 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:49:27.592708 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:49:27.592723 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:49:27.592732 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:49:27.592742 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:49:27.592752 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:49:27.592774 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-03-07 21:49:27.592785 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-03-07 21:49:27.592795 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-03-07 21:49:27.592805 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-03-07 21:49:27.592815 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-03-07 21:49:27.592825 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-03-07 21:49:27.592835 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-03-07 21:49:27.592845 2023-03-07 21:49:27.589 39 ERROR keystone.server.flask.application \x1b[00m
2023-03-07 21:49:28.444580 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application [None req-6ff032b9-ca54-48d3-a2d0-648e85da36f2 9686372be73d4d269440f3838c70b399 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:49:28.444629 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-03-07 21:49:28.444644 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-03-07 21:49:28.444689 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-03-07 21:49:28.444702 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-03-07 21:49:28.444712 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-03-07 21:49:28.444722 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-03-07 21:49:28.444732 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-03-07 21:49:28.444751 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-03-07 21:49:28.444769 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-03-07 21:49:28.444781 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-03-07 21:49:28.444791 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-03-07 21:49:28.444801 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-03-07 21:49:28.444811 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-03-07 21:49:28.444821 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-03-07 21:49:28.444830 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-03-07 21:49:28.444857 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-03-07 21:49:28.444870 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-03-07 21:49:28.444879 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-03-07 21:49:28.444889 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-03-07 21:49:28.444922 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-03-07 21:49:28.444949 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self.get_or_create(
2023-03-07 21:49:28.444960 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-03-07 21:49:28.444970 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     with Lock(
2023-03-07 21:49:28.444980 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-03-07 21:49:28.444990 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self._enter()
2023-03-07 21:49:28.444999 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-03-07 21:49:28.445009 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-03-07 21:49:28.445019 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-03-07 21:49:28.445029 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self.creator()
2023-03-07 21:49:28.445039 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-03-07 21:49:28.445049 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     created_value = creator(
2023-03-07 21:49:28.445059 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-03-07 21:49:28.445069 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-03-07 21:49:28.445079 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-03-07 21:49:28.445089 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-03-07 21:49:28.445099 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-03-07 21:49:28.445113 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-03-07 21:49:28.445126 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-03-07 21:49:28.445136 2023-03-07 21:49:28.440 38 ERROR keystone.server.flask.application \x1b[00m
2023-03-08 02:18:53.104982 2023-03-08 02:18:53.102 37 WARNING py.warnings [None req-a589c6d7-4fd2-410d-b2d3-fe11dd5e5afa 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_domains": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:53.105085   warnings.warn(msg)
2023-03-08 02:18:53.105101 \x1b[00m
2023-03-08 02:18:53.444248 2023-03-08 02:18:53.442 38 WARNING py.warnings [None req-a37ba1cb-37b8-4727-b94c-da5d25a1f2b6 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_project": "(role:admin and system_scope:all) or (role:admin and domain_id:%(target.project.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:53.444296   warnings.warn(msg)
2023-03-08 02:18:53.444308 \x1b[00m
2023-03-08 02:18:53.736852 2023-03-08 02:18:53.735 39 WARNING py.warnings [None req-403b89cb-afc0-4150-9951-b56c37b370b4 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_user": "(role:admin and system_scope:all) or (role:admin and token.domain.id:%(target.user.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:53.736901   warnings.warn(msg)
2023-03-08 02:18:53.736914 \x1b[00m
2023-03-08 02:18:54.627574 2023-03-08 02:18:54.626 37 WARNING py.warnings [None req-ef98c19f-d75b-457f-9042-85c199a3c0e5 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:54.627631   warnings.warn(msg)
2023-03-08 02:18:54.627642 \x1b[00m
2023-03-08 02:18:54.950132 2023-03-08 02:18:54.948 38 WARNING py.warnings [None req-d749143e-91cd-4143-a243-cd3e019030f5 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:54.950247   warnings.warn(msg)
2023-03-08 02:18:54.950261 \x1b[00m
2023-03-08 02:18:56.115510 2023-03-08 02:18:56.114 37 WARNING py.warnings [None req-25fb03f3-373f-4121-99f1-2f9a6e74a007 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_project": "(role:admin and system_scope:all) or (role:admin and domain_id:%(target.project.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:56.115649   warnings.warn(msg)
2023-03-08 02:18:56.115663 \x1b[00m
2023-03-08 02:18:56.586754 2023-03-08 02:18:56.585 38 WARNING py.warnings [None req-763b0cef-d8ca-4647-a2fa-fd164126cb4d 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_user": "(role:admin and system_scope:all) or (role:admin and token.domain.id:%(target.user.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:56.586835   warnings.warn(msg)
2023-03-08 02:18:56.586848 \x1b[00m
2023-03-08 02:18:57.503736 2023-03-08 02:18:57.502 39 WARNING py.warnings [None req-8ab68766-75b7-4729-8112-a16aa74e26f6 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:57.503780   warnings.warn(msg)
2023-03-08 02:18:57.503791 \x1b[00m
2023-03-08 02:18:57.800454 2023-03-08 02:18:57.799 37 WARNING py.warnings [None req-e02204ff-700a-4e6a-9c9a-3939a926a442 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:57.800503   warnings.warn(msg)
2023-03-08 02:18:57.800514 \x1b[00m
2023-03-08 02:18:58.005851 2023-03-08 02:18:58.004 38 WARNING py.warnings [None req-fbfae861-42de-41c2-874d-ac18c1285023 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:list_roles": "role:reader and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:58.005896   warnings.warn(msg)
2023-03-08 02:18:58.005908 \x1b[00m
2023-03-08 02:18:58.267885 2023-03-08 02:18:58.267 39 WARNING py.warnings [None req-cb2fee68-de44-4cf0-b83d-0d86704534f1 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_grant": "(role:admin and system_scope:all) or ((role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.user.domain_id)s and domain_id:%(target.domain.id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.project.domain_id)s) or (role:admin and domain_id:%(target.group.domain_id)s and domain_id:%(target.domain.id)s)) and (domain_id:%(target.role.domain_id)s or None:%(target.role.domain_id)s)" failed scope check. The token used to make the request was project scoped but the policy requires ['system', 'domain'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:18:58.267964   warnings.warn(msg)
2023-03-08 02:18:58.267977 \x1b[00m
2023-03-08 02:19:00.566313 2023-03-08 02:19:00.565 37 WARNING py.warnings [None req-10415109-34f6-439d-8c1e-bc646f77750f 9686372be73d4d269440f3838c70b399 04074ead6e2c4077bc8630aaf9d3b265 - - default default] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1129: UserWarning: Policy "identity:create_system_grant_for_user": "role:admin and system_scope:all" failed scope check. The token used to make the request was project scoped but the policy requires ['system'] scope. This behavior may change in the future where using the intended scope is required
2023-03-08 02:19:00.566358   warnings.warn(msg)
2023-03-08 02:19:00.566370 \x1b[00m
