2023-04-25 20:49:41.576 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-25 20:49:41.579 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-25 20:49:41.619 23 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2023-04-25 20:49:41.620 23 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2023-04-25 20:49:41.682 23 INFO alembic.runtime.migration [-] Running upgrade  -> 27e647c0fad4, Initial version.
2023-04-25 20:49:43.072 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> e25ffa003242, Initial no-op Yoga contract migration.
2023-04-25 20:49:43.080 23 INFO alembic.runtime.migration [-] Running upgrade 27e647c0fad4 -> 29e87d24a316, Initial no-op Yoga expand migration.
2023-04-25 20:49:51.468 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-25 20:49:51.473 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-25 20:49:51.474 7 INFO keystone.common.fernet_utils [-] Starting key rotation with 1 key files: ['/etc/keystone/fernet-keys/0']
2023-04-25 20:49:51.476 7 INFO keystone.common.fernet_utils [-] Created a new temporary key: /etc/keystone/fernet-keys/0.tmp
2023-04-25 20:49:51.476 7 INFO keystone.common.fernet_utils [-] Current primary key is: 0
2023-04-25 20:49:51.477 7 INFO keystone.common.fernet_utils [-] Next primary key will be: 1
2023-04-25 20:49:51.478 7 INFO keystone.common.fernet_utils [-] Promoted key 0 to be the primary: 1
2023-04-25 20:49:51.479 7 INFO keystone.common.fernet_utils [-] Become a valid new key: /etc/keystone/fernet-keys/0
2023-04-25 20:50:10.908 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created domain default
2023-04-25 20:50:10.979 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created project admin
2023-04-25 20:50:11.643 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created user admin
2023-04-25 20:50:11.666 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created role reader
2023-04-25 20:50:11.686 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created role member
2023-04-25 20:50:11.725 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created implied role where dd15e07961da47179c041aa1e90b5ee2 implies 6f7bf2d81e8d4ac0841b26e853c49892
2023-04-25 20:50:11.743 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created role admin
2023-04-25 20:50:11.774 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created implied role where a2033dc2777e4802bba2d3a1378853b3 implies dd15e07961da47179c041aa1e90b5ee2
2023-04-25 20:50:11.796 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Granted role admin on project admin to user admin.
2023-04-25 20:50:11.806 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Granted role admin on the system to user admin.
2023-04-25 20:50:11.830 148 WARNING py.warnings [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] /var/lib/kolla/venv/lib/python3.9/site-packages/pycadf/identifier.py:71: UserWarning: Invalid uuid: RegionOne. To ensure interoperability, identifiers should be a valid uuid.
  warnings.warn(('Invalid uuid: %s. To ensure interoperability, '

2023-04-25 20:50:11.836 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created region RegionOne
2023-04-25 20:50:11.884 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created public endpoint http://169.16.1.184:5000
2023-04-25 20:50:11.896 148 INFO keystone.cmd.bootstrap [None req-3f02f626-5e9d-4908-8d15-20873e1d0434 - - - - - -] Created internal endpoint http://169.16.1.184:5000
2023-04-25 20:50:38.149 26 WARNING keystone.common.rbac_enforcer.enforcer [None req-46f1c5d2-fb87-4121-9750-ab606c48266a 01955478db064f4cb13edc9caf19d478 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 20:50:38.978 28 WARNING keystone.common.rbac_enforcer.enforcer [None req-47068f11-89b1-4a9e-b4de-4f02541e0345 01955478db064f4cb13edc9caf19d478 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 20:50:47.535 27 WARNING keystone.common.rbac_enforcer.enforcer [None req-917fd84a-cdaa-47b3-8559-a6f5553dfa4c 01955478db064f4cb13edc9caf19d478 - - all default -] Deprecated policy rules found. Use oslopolicy-policy-generator and oslopolicy-policy-upgrade to detect and resolve deprecated policies in your configuration.
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application [None req-2d102229-00cf-4a02-86d2-8b59e31a34e9 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:09.021 26 ERROR keystone.server.flask.application 
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application [None req-45857e78-bb22-4599-9180-c50b1b7f6b5d 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:19.631 27 ERROR keystone.server.flask.application 
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application [None req-e74d9700-964e-443c-8864-5017615bd0ab 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:52:36.102 27 ERROR keystone.server.flask.application 
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application [None req-be9caeef-d504-41ac-bd50-398b202be1c7 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find user: ironic.: keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic.
2023-04-25 20:52:37.481 27 ERROR keystone.server.flask.application 
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application [None req-0e4e40e9-c614-457e-9d66-ec9a47beeb2a 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:38.488 28 ERROR keystone.server.flask.application 
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application [None req-99a19649-84c7-4bb1-aea2-5be24b1a4a88 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:52:49.524 26 ERROR keystone.server.flask.application 
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application [None req-8ac062c4-0b96-472f-bcbe-6a1f69318502 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find user: ironic-inspector.: keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: ironic-inspector.
2023-04-25 20:52:51.100 26 ERROR keystone.server.flask.application 
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application [None req-92c6d7db-f6df-4ba7-b351-c08c8555a50c 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:52:51.968 27 ERROR keystone.server.flask.application 
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application [None req-b4062b59-d3f9-44bb-b11b-39e86ffe855a 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:55:55.355 28 ERROR keystone.server.flask.application 
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application [None req-97d1d5ae-be2c-4081-aba0-60b777ebc123 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find role: admin.: keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 50, in get
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self._get_role(role_id)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/roles.py", line 70, in _get_role
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     ENFORCER.enforce_call(action='identity:get_role')
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 402, in enforce_call
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     policy_dict.update(cls._extract_member_target_data(
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/rbac_enforcer/enforcer.py", line 234, in _extract_member_target_data
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     member_name: func(flask.request.view_args[key])
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/core.py", line 1276, in get_role
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self.driver.get_role(role_id)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 70, in get_role
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     return self._get_role(session, role_id).to_dict()
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/assignment/role_backends/sql.py", line 65, in _get_role
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application     raise exception.RoleNotFound(role_id=role_id)
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application keystone.exception.RoleNotFound: Could not find role: admin.
2023-04-25 20:56:09.822 27 ERROR keystone.server.flask.application 
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application [None req-cbb90cf5-3b27-4852-b1c0-1f202c33088d 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find user: neutron.: keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 182, in get
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return self._get_user(user_id)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/users.py", line 194, in _get_user
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     ref = PROVIDERS.identity_api.get_user(user_id)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 414, in wrapper
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 424, in wrapper
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return f(self, *args, **kwargs)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/core.py", line 1011, in get_user
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     ref = driver.get_user(entity_id)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 200, in get_user
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     self._get_user(session, user_id).to_dict())
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/identity/backends/sql.py", line 194, in _get_user
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application     raise exception.UserNotFound(user_id=user_id)
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application keystone.exception.UserNotFound: Could not find user: neutron.
2023-04-25 20:56:11.001 27 ERROR keystone.server.flask.application 
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application [None req-f92e6f93-83d6-47c0-b3e4-b4d49feb04ef 01955478db064f4cb13edc9caf19d478 - - all default -] Could not find project: service.: keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application Traceback (most recent call last):
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     rv = self.dispatch_request()
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     resp = resource(*args, **kwargs)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     resp = meth(*args, **kwargs)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 151, in get
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self._get_project(project_id)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/api/projects.py", line 107, in _get_project
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     project = PROVIDERS.resource_api.get_project(project_id)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/common/manager.py", line 115, in wrapped
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     __ret_val = __f(*args, **kwargs)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return caller(func, *(extras + args), **kw)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self.get_or_create(
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 1042, in get_or_create
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     with Lock(
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 185, in __enter__
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self._enter()
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 94, in _enter
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     generated = self._enter_create(value, createdtime)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/lock.py", line 178, in _enter_create
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self.creator()
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/dogpile/cache/region.py", line 995, in gen_value
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     created_value = creator(
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/core.py", line 903, in get_project
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self.driver.get_project(project_id)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 49, in get_project
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     return self._get_project(session, project_id).to_dict()
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application   File "/var/lib/kolla/venv/lib/python3.9/site-packages/keystone/resource/backends/sql.py", line 44, in _get_project
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application     raise exception.ProjectNotFound(project_id=project_id)
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application keystone.exception.ProjectNotFound: Could not find project: service.
2023-04-25 20:56:11.750 28 ERROR keystone.server.flask.application 
